chhotu/accounts/urls.py
from django.conf.urls import url
from accounts import apis, views

urlpatterns = [
    url(r'^register/$', apis.Register.as_view(), name="register"),
    url(r'^login/$', apis.Login.as_view(), name="login"),
    url(r'^logout/$', apis.LogOut.as_view(), name='logout'),
    url(r'^address/$', apis.UserAddressApi.as_view(), name="user-address-api"),
    url(r'^address/(?P<pk>\d+)/$', apis.UserAddressDetail.as_view(), name="api_update_useraddress"),
    url(r'^forgot-password/$', apis.ForgotPasswordApi.as_view(), name="forgot-password-api"),
    url(r'^password-reset/(?P<username>.*)/(?P<activation_key>.*)/$', apis.ResetPasswordApi.as_view(), name="api_reset_password"),
    url(r'^authenticate/$', apis.UserAuthenticate.as_view(), name="api_authenticate"),
]

chhotu/chhotu/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^docs/', include('rest_framework_docs.urls')),
    url(r'^auth/', include('accounts.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^data/', include('miscdata.urls')),
    url(r'^payments/', include('payments.urls')),
]

chhotu/home/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.views.decorators.csrf import csrf_exempt

from home import views

urlpatterns = [
    url(r'^register/$', views.RegisterView.as_view(), name="registration_view"),
    url(r'^login/$', views.LoginView.as_view(), name="login_view"),

    url(r'^$', views.HomeView.as_view(), name="home_view"),
    url(r'^product/$', views.ProductView.as_view(), name="product_view"),
    url(r'^cart/$', views.CartView.as_view(), name="cart_view"),
    url(r'^order/addressselect/$', views.AddressView.as_view(), name="address_view"),
    url(r'^order/payment/$', views.OrderPaymentView.as_view(), name="orderpayment_view"),
    url(r'^order-complete/$', csrf_exempt(views.OrderCompleteView.as_view()), name="order_success_view"),

    url(r'^admin-portal/$', views.AdminOrderView.as_view(), name="adminportal_view"),
    url(r'^redirect/$', RedirectView.as_view(url="/order-success/"), name="redirect_view"),

    url(r'^about-us/$', views.AboutUsView.as_view(), name="aboutus_view"),
    url(r'^terms/$', views.TermsConditionView.as_view(), name="terms_condition_view"),
    url(r'^privacy-policy/$', views.PrivacyPolicyView.as_view(), name="privacy_policy_view"),
    url(r'^refund-policy/$', views.RefundPolicyView.as_view(), name="refund_policy_view"),
    url(r'^contact-us/$', views.ContactUsView.as_view(), name="contact_view")
]

chhotu/accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import RegexValidator, MinLengthValidator, MaxLengthValidator

import uuid
import hashlib
from random import choice
from string import lowercase

from .managers import ProfileManager, UserAddressManager


def user_image_upload(instance, filename):
    return "profile_images/user%s" % (filename)

ADMIN = "1"
CUSTOMER = "2"
DELIVERY = "3"

USER_ROLE_CHOICES = [
    (ADMIN, "Admin"),
    (CUSTOMER, "Customer/User"),
    (DELIVERY, "Delivery Boy")
]


class Profile(AbstractBaseUser, PermissionsMixin):
    """
    user model containing user's info
    as name/email/username/address
    """
    name = models.CharField(_("Your Name"), max_length=120)
    email = models.EmailField(_("Email"), max_length=70, unique=True)
    username = models.CharField(_("Profilename"), max_length=32, unique=True)
    contact_no = models.CharField(_("Contact Number"), max_length=15, validators=[
        RegexValidator(r'^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$'),
        MinLengthValidator(6),
        MaxLengthValidator(15),
        ])
    image = models.FileField(_("Image"), default="user-default.png", upload_to=user_image_upload)
    about = models.TextField(_("About"), blank=True, null=True)
    facebook_profiile = models.URLField(_("Facebook Profile"), blank=True, null=True)
    twitter_profile = models.URLField(_("Twitter Profile"), blank=True, null=True)
    role = models.CharField(
        _("Profile Role"), max_length=1, choices=USER_ROLE_CHOICES, default=2)
    email_alerts = models.BooleanField(_("Email Alerts"), default=False)
    sms_alerts = models.BooleanField(_("SMS Alerts"), default=False)
    is_staff = models.BooleanField(
        _("Staff Status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."))

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_("Designates whether this user should be treated as "
                    "active. Unselect this instead of deleting accounts."))
    date_joined = models.DateTimeField(_("Date Joined"), auto_now_add=True)
    uuid = models.UUIDField(_("Profile Unique ID"), default=uuid.uuid4, editable=False)
    created = models.DateTimeField(_("Created On"), auto_now_add=True)
    updated = models.DateTimeField(_("Updated On"), auto_now=True)
    delete = models.BooleanField(_("Delete"), default=False)

    objects = ProfileManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")
        app_label = "accounts"

    def __unicode__(self):
        return "%s" % (self.email)

    def save(self, *args, **kwargs):
        """
        ensure instance has usable password when created &
        add username by default when saving user
        """
        if self.pk is None:
            name = "_".join(str(self.name).split()).replace(".", "_")
            self.username = name.lower() + '_' + ''.join([choice(lowercase) for i in xrange(3)])
        if not self.pk and self.has_usable_password() is False:
            self.set_password(self.password)

        super(Profile, self).save(*args, **kwargs)

    def get_full_name(self):
        """
        return user's full name i.e. first_name and last_name
        """
        return "%s" % (self.name)

    def get_short_name(self):
        return "%s" % (self.name)

    def generate_token(self):
        #salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
        salt = uuid.uuid4().hex[:5]
        activation_key = hashlib.sha1(salt+self.username).hexdigest()
        return activation_key


class UserAddress(models.Model):
    """
    user-address mapping model
    """
    user = models.ForeignKey(Profile, related_name=_("useraddress"))
    address = models.TextField(_("Address"))
    landmark = models.CharField(_("landmark"), max_length=200, blank=True, null=True)
    city = models.CharField(_("City"), max_length=40, default='Gurgaon')
    state = models.CharField(_("State"), max_length=40, default='Haryana')
    country = models.CharField(_("Country"), max_length=40, default='IN')
    zipcode = models.IntegerField(_("Zip Code"), default=122001)
    delete = models.BooleanField(_("Delete"), default=False)

    objects = UserAddressManager()

    class Meta:
        verbose_name = _("UserAddress")
        verbose_name_plural = _("UserAddresses")
        app_label = "accounts"

    def __unicode__(self):
        return "%s" % (self.address)


class PasswordResetManager(models.Manager):
    """
    manager for password reset
    """
    def create_for_user(self, user):
        """ create password reset for specified user """
        # support passing email address too
        if type(user) is unicode:
            user = Profile.objects.get(email=user)
        activation_key = user.generate_token()
        # save it to the password reset model
        reset_instance = PasswordReset(user=user, activation_key=activation_key)
        reset_instance.save()
        return reset_instance


class PasswordReset(models.Model):
    user = models.ForeignKey(Profile, verbose_name=_("user"))
    activation_key = models.CharField(_("activation_key"), max_length=100)

    objects = PasswordResetManager()

    class Meta:
        verbose_name = _('PasswordReset')
        verbose_name_plural = _('PasswordResets')
        app_label = "accounts"

    def __unicode__(self):
        return "%s" % (self.activation_key)

chhotu/home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

chhotu/home/templates/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate
from accounts.models import Profile as User
from django.contrib import auth
from django.core.exceptions import ValidationError


class OrderPaymentForm(forms.Form):
    """
    Form for login a user.
    """
    key = forms.EmailField(widget=forms.TextInput, label=_("Merhant Key"))
    txnid = forms.CharField(widget=forms.TextInput, label=_("Order UUID"))
    amount = forms.CharField(widget=forms.TextInput, label=_("Order Payable Amount"))
    productinfo = forms.CharField(widget=forms.TextInput, label=_("Order UUID"))
    firstname = forms.CharField(widget=forms.TextInput, label=_("Buyer Name"))
    email = forms.CharField(widget=forms.TextInput, label=_("Buyer Email"))
    udf1 = forms.CharField(widget=forms.TextInput, label=_("Delivery Address"))
    udf2 = forms.CharField(widget=forms.TextInput, label=_("Ordered At"))
    udf3 = forms.CharField(widget=forms.TextInput, label=_("Delivery DateTime"))
    udf4 = forms.CharField(widget=forms.TextInput, label=_("Merchant Salt"))
    phone = forms.CharField(widget=forms.TextInput, label=_("Phone"))
    surl = forms.CharField(widget=forms.TextInput, label=_("Success URL"))
    furl = forms.CharField(widget=forms.TextInput, label=_("Failure URL"))
    curl = forms.CharField(widget=forms.TextInput, label=_("Cancel URL"))
    hash = forms.CharField(widget=forms.TextInput, label=_("Hash"))

chhotu/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.base import TemplateView
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.views.generic import View
from django.template import Context
from django.template.loader import get_template
from django.core.mail import EmailMessage

import datetime
from hashlib import sha512
import uuid
from braces.views import AnonymousRequiredMixin, LoginRequiredMixin

from orders.models import Order, OrderDetail
from payments.models import OrderAmount, PaymentDetail


class RegisterView(AnonymousRequiredMixin, TemplateView):
    """
    view to render register template
    """
    authenticated_redirect_url = settings.LOGIN_REDIRECT_URL
    template_name = "accounts/register.html"


class LoginView(AnonymousRequiredMixin, TemplateView):
    """
    view to render login template
    """
    authenticated_redirect_url = settings.LOGIN_REDIRECT_URL
    template_name = "accounts/login.html"


class HomeView(TemplateView):
    """
    landing page/index page views
    """
    template_name = "home/index.html"

    def get(self, request, *args, **kwargs):
        _urcpid = uuid.uuid4()
        _gpduid = uuid.uuid4()
        max_age = 12 * 60
        expires = datetime.datetime.strftime(datetime.datetime.utcnow() + datetime.timedelta(seconds=max_age), "%a, %d-%b-%Y %H:%M:%S GMT")
        response = render(request, self.template_name)
        response.set_cookie('urcpid', _urcpid, max_age=max_age, expires=expires)
        response.set_cookie('gpduid', _gpduid, max_age=max_age, expires=expires)
        return response


class ProductView(TemplateView):
    """
    product template view
    """
    template_name = "order/product.html"


class CartView(TemplateView):
    """
    cart template view
    """
    template_name = "order/cart.html"


class AddressView(LoginRequiredMixin, TemplateView):
    """
    view to render address template for user detail and update its details
    """
    login_url = "/"
    template_name = "order/address.html"

    def get(self, request, *args, **kwargs):
        response = render(request, self.template_name)
        response.delete_cookie('urcpid')
        response.delete_cookie('gpduid')
        return response


class OrderPaymentView(LoginRequiredMixin, TemplateView):
    """
    view to render order payment template
    """
    login_url = "/"
    template_name = "payments/payment.html"

    def get_context_data(self, **kwargs):
        context = super(OrderPaymentView, self).get_context_data(**kwargs)
        if not self.request.GET.get('order__ppk'):
            order = Order.objects.filter(user=self.request.user).order_by('-ordered_at')[0]
        else:
            order = Order.objects.get(id=self.request.GET.get('order__ppk'))
        context['order'] = order
        context['orders'] = OrderDetail.objects.filter(order=order)
        ctype = ContentType.objects.get_for_model(order)
        context['order_amount'] = OrderAmount.objects.get(content_type=ctype, object_id=order.id)
        context['merchant_key'] = settings.PAYU_MERCHANT_KEY
        context['merchant_salt'] = settings.PAYU_MERCHANT_SALT
        context['payment_url'] = settings.PAYU_PAYMENT_URL
        context['domain'] = self.request.build_absolute_uri("/").rstrip("/")
        key = str(settings.PAYU_MERCHANT_KEY)
        txnid = str(context["order"].uuid)
        amount = str(context["order_amount"].payable_amount)
        productinfo = str(context["order"].uuid)
        firstname = str(context["order"].user.name)
        email = str(context['order'].user.email)
        salt = str(settings.PAYU_MERCHANT_SALT)
        context['hash'] = sha512(key+"|"+txnid+"|"+amount+"|"+productinfo+"|"+firstname+"|"+email+"|"+"|"+"|"+"|"+"|"+"|"+"|"+"|"+"|"+"|"+"|"+salt).hexdigest()
        return context


class AdminOrderView(LoginRequiredMixin, TemplateView):
    """
    order review and submit order
    """
    login_url = "/"
    template_name = "admin/orders.html"


class OrderCompleteView(View):
    """
    view to render success template
    """
    def get(self, request):
        order = Order.objects.get(id=request.GET.get('order__ppk'))
        self._inform_user(order.uuid)
        context = {'status': "success"}
        return render(request, 'order/order-complete.html', context)

    def post(self, request):
        PaymentDetail.objects.create(
            payu_id=request.POST['mihpayid'], mode=request.POST['mode'], status=request.POST['status'],
            key=request.POST['key'], txnid=request.POST['txnid'], amount=request.POST['amount'],
            email=request.POST['email'], hash=request.POST['hash'])
        self._inform_user(request.POST['txnid'])
        context = {'status': request.POST['status']}
        return render(request, 'order/order-complete.html', context)

    def _inform_user(self, txnid):
        subject = "Order Detail Confirmation"
        to = [self.request.user.email, ]
        from_email = 'order@urschottu.com'
        order = Order.objects.get(uuid=txnid)
        orders = OrderDetail.objects.filter(order=order)
        ctx = {
            'user': self.request.user,
            'orders': orders
        }
        message = get_template('mail/orders.html').render(Context(ctx))
        msg = EmailMessage(subject, message, to=to, from_email=from_email)
        msg.content_subtype = 'html'
        msg.send()
        from twilio.rest import TwilioRestClient
        accountSid = settings.TWILIO_SID
        authToken = settings.TWILIO_AUTH_TOKEN
        twilioClient = TwilioRestClient(accountSid, authToken)
        myTwilioNumber = "+1 928-362-3296 "
        destCellPhone = '+91 9467116467'
        ORDER_LIST = ", ".join([item.product.name for item in orders])
        msgtext = "Hi "+self.request.user.name+" Your order " + ORDER_LIST + " has been successfully placed.All items in your ordered will be delivered within 49 mins."
        twilioClient.messages.create(body=msgtext, from_=myTwilioNumber, to=destCellPhone)
        # from sendsms.message import SmsMessage
        # message = SmsMessage(body=msgtext, from_phone='+919467116467', to=['+917061251325'])
        # message.send()


class AboutUsView(TemplateView):
    """
    view to render about us template
    """
    template_name = "home/about-us.html"


class TermsConditionView(TemplateView):
    """
    terms n condition
    """
    template_name = "home/terms-condition.html"


class PrivacyPolicyView(TemplateView):
    """
    view to render privacy policy template
    """
    template_name = "home/privacy.html"


class RefundPolicyView(TemplateView):
    """
    view to render refund policy template
    """
    template_name = "home/refund.html"


class ContactUsView(TemplateView):
    """
    view to render contact us template
    """
    template_name = "home/contact.html"

chhotu/home/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	Home Page
{% endblock %}
{% block content %}
<section class="container" style="background-color: #fff;width:1300px;max-width:1357px;height:100%;">
	<div class="row pd-20">
		<div class="col-sm-12">
			<div class="col-sm-2">
				<a href="/"><i class="fa fa-arrow-left" style="font-size:1.4em;"></i> Back To Home</a>
			</div>
			<div class="col-sm-offset-3 col-sm-7">
				<img src="{% static 'images/chotu-logo3.png' %}" class="img-responsive" width="150px">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<form class="form-horizontal" id="login_form">
				<h3 class="text-left" style="margin-top: 10px;margin-bottom:5px;">Sign in</h3>
				<div class="form-group">
					<label class="control-label">Email</label>
					<input type="text" class="form-control" name="email" placeholder="Email Address" id="id_username" tabindex="1" required>
				</div>
				<div class="form-group">
					<label class="control-label">Password</label><span class="pull-right" style="padding-top: 7px;"><a href="/forgot-password/"> Forgot you password?</a></span>
					<input type="password" class="form-control" name="password" placeholder="Password" id="id_password" tabindex="2" required>
				</div>
				<div class="form-group text-center">
					<input type="submit" taindex="3" id="register_submit" class="btn btn-info full-width" value="Sign in">
				</div>
				<div class="p-devider">
					<h5 class="text-center"><span>New to Chhotu?</span></h5>
				</div>
				<div class="form-group text-center">
					<a href="/register/" class="btn btn-secondary full-width" id="id_registerUser">Create your account now</a>
				</div>
				<p class="tiny">By signing in, you are agreeing to our <a href="#">Conditions of Use and order</a> and <a href="#">Privacy Notice.</a></p>
			</form>
		</div>
	</div>
	<div class="a-devider"></div>
	<div class="row centered">
		<div class="col-sm-12">
			<p class="text-center tiny">
				<a href="#" class="pdlr-20">Help</a>
				<a href="#" class="pdlr-20">Conditions of Use</a>
				<a href="#" class="pdlr-20">Privacy Notice</a>
			</p>
			<p class="text-center tiny">© 1996-2016, Chhotu.com, Inc. or its affiliates</p>
		</div>
	</div>
</section>
{% endblock %}
{% block extrascript %}
<script type="text/javascript" src="{% static 'js/chhotu/login.js' %}"></script>
{% endblock %}

chhotu/home/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	Home Page
{% endblock %}
{% block content %}
<section class="container" style="background-color: #fff;width:1300px;max-width:1357px;">
	<div class="row pd-20">
		<div class="col-sm-12">
			<div class="col-sm-2">
				<a href="/"><i class="fa fa-arrow-left" style="font-size:1.4em;"></i> Back To Home</a>
			</div>
			<div class="col-sm-offset-3 col-sm-7">
				<img src="{% static 'images/chotu-logo3.png' %}" class="img-responsive" width="150px">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<form class="form-horizontal" id="register_form">
				<h3 class="text-left" style="margin-top: 10px;margin-bottom:5px;">Create Account</h3>
				<div class="form-group">
					<label class="control-label">Your Name</label>
					<input type="text" class="form-control" name="name" placeholder="Your Name" id="id_name" required>
				</div>
				<div class="form-group">
					<label class="control-label">Email</label>
					<input type="text" class="form-control" name="email" placeholder="Your Email" id="id_email" required>
				</div>
				<div class="form-group">
					<label class="control-label">Mobile</label>
					<input type="text" class="form-control" name="contact_no" placeholder="Your Mobile" id="id_mobile" required>
				</div>
				<div class="form-group">
					<label class="control-label">Password</label>
					<input type="password" class="form-control" name="password" placeholder="Password" id="id_password" required>
				</div>
				<div class="form-group text-center">
					<input type="submit" id="register_submit" class="btn btn-info full-width" value="Create Your Account">
				</div>
				<p class="tiny">By creating an account, you agree to chhotu.com's <a href="#">Conditions of Use</a> and <a href="#">Privacy Notice.</a></p>
				<div class="a-devider"></div>
				<p class="tiny no-margin">Already have an account? <a href="/login/">Sign in</a></p>
			</form>
		</div>
	</div>
	<div class="a-devider"></div>
	<div class="row centered">
		<div class="col-sm-12">
			<p class="tiny">
				<a href="#" class="pdlr-20">Help</a>
				<a href="#" class="pdlr-20">Conditions of Use</a>
				<a href="#" class="pdlr-20">Privacy Notice</a>
			</p>
			<p class="tiny">© 1996-2016, StuffonRent.com, Inc. or its affiliates</p>
		</div>
	</div>
</section>
{% endblock %}
{% block extrascript %}
<script type="text/javascript" src="{% static 'js/chhotu/register.js' %}"></script>
{% endblock %}